version: '3.8'

services:
 app:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  command: >
    sh -c "python app.py"
    sh -c "pytest"

 test:
  build:
   context: .
  volumes:
   - ./tests/:/app/tests
  command: >
   sh -c "python -m pytest -s -v"